apiVersion: apps/v1
kind: Deployment
metadata:
  name: finops-secure-eks-gitops-pipeline
  labels:
    app: finops-secure-eks-gitops-pipeline
    team: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finops-secure-eks-gitops-pipeline
  template:
    metadata:
      labels:
        app: finops-secure-eks-gitops-pipeline
        team: frontend
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: finops-secure-eks-gitops-pipeline
          image: sadikgok/finops-secure-eks-gitops-pipeline:11
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
