apiVersion: v1
kind: Service
metadata:
  name: finops-secure-eks-gitops-pipeline
  labels:
    app: finops-secure-eks-gitops-pipeline
    team: frontend
spec:
  type: NodePort
  selector:
    app: finops-secure-eks-gitops-pipeline
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30080